### ISSUE TITLE
TTL needs cts:belongsTo and cts:possesses for non-leaf-node citations

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/hocuspocus#50]
Currently, when we TTLize:

<urn:cts:greekLit:tlg7000.tlg001.msA:9.385.3> cts:belongsTo <urn:cts:greekLit:tlg7000.tlg001.msA:> .

But not:

<urn:cts:greekLit:tlg7000.tlg001.msA:9.385> cts:belongsTo <urn:cts:greekLit:tlg7000.tlg001.msA:> .
or
<urn:cts:greekLit:tlg7000.tlg001.msA:9> cts:belongsTo <urn:cts:greekLit:tlg7000.tlg001.msA:> .

**Comment by neelsmith** [comment]
I see a subordinate clause but no principal clause in the comment:  what scholiastic compression should I expand this to?'

**Comment by neelsmith** [comment]
CLosing: superceded by #53
