### ISSUE TITLE
cts:contains with citation-depth > 2

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/hocuspocus#51]
We currently get:
<urn:cts:greekLit:tlg7000.tlg001.msA:9> cts:contains <urn:cts:greekLit:tlg7000.tlg001.msA:9.387.1>
(and all other leaf-nodes)

But not:

<urn:cts:greekLit:tlg7000.tlg001.msA:9> cts:contains <urn:cts:greekLit:tlg7000.tlg001.msA:9.387>

**Comment by neelsmith** [comment]
Closing: superseded by others including #53
