### ISSUE TITLE
Tabulation/TTLization runs out of heap space on very long texts

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/hocuspocus#67]
Tabulation/TTLization runs out of heap space on very long texts. Longer than an Iliad, but shorter than an Iliad with each word citable.

**Comment by neelsmith** [comment]
Not a bug, even if it's not the most desirable feature of the library.  Response:

1. hocuspocus supports in-memory tabulation/ttl'ziation (and therefore is reasonably fast)
2. options for handling very large texts:
    - set ginormous heap space when running
    - segment your text before tabulating/ttl'izing

Closing this issue out after our recent phone conversation.
